---
title: BOUT++ Project
short_title: BOUT++
author: BOUT++ Project
author_github: boutproject
locale: en
description: |
  Plasma simulation in curvilinear coordinate systems
baseurl: "/"
url: https://boutproject.github.io
paginate: 12
github:
  user: boutproject
  repository: boutproject.github.io
  url: https://boutproject.github.io/
  status: false
home_bgfile: bout_banner.png
sass:
  sass_dir: assets/css
  style: compressed
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
- jekyll-paginate
- jekyll-seo-tag
exclude:
- vendor
collections:
  applications:
    output: true
    permalink: /applications/:title
defaults:
  # Defaults for applications collection
  - scope:
      path: ""
      type: applications
    values:
      layout: applications
      excerpt_separator: <!--more-->

# Config for running site locally
localtest: false
localurl: http://localhost:4000/
